# Site settings
title: Leopolis – Research & Design
description: > # this means to ignore newlines until "url:"
  Wskazujemy drogę w świecie paradoksów społecznych. Zapewniamy wsparcie twoim projektom.
url: "http://leopolisrd.pl"